title: Jill Tipton # your name (or website title) here
logo: "/images/2.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <a href="https://drive.google.com/file/d/1kZpFV_2Q4WUg9XOAYFo0Le7BWypJrwhb/view?usp=sharing">Résumé (English)</a> | <a href="https://drive.google.com/file/d/1xZHNhVsn_y7vSoyvSRnOhmFjJgMpKUky/view?usp=sharing">CV (français)</a> | <a href="https://drive.google.com/file/d/1vBRhDwX7SqaDa0IHC2VhHzai9xcf0nD1/view?usp=sharing"> Portfolio (français)</a> | <a href="https://www.linkedin.com/in/jill-ti/">LinkedIn</a> | <a href="https://docs.google.com/forms/d/e/1FAIpQLSdaM0dB94QPEt9lZqslmL7no4zA9TQ5sY0UnriuiNYZ7fjk-w/viewform?usp=sf_link">Contact Me</a>
google_analytics: UA-171045601-1 # your Google Analytics tracking ID here
theme: jekyll-theme-minimal

