title: Jill Tipton # your name (or website title) here
logo: "/images/641158C6-761D-4D22-88CC-DFF1E73252FE.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A former social science researcher who transitioned to UX Research, I execute quantitative and qualitative research studies to support design decisions and drive product initiatives. My favorite question is “Why?” and I use the answers to help make people's lives easier and better. My greatest strength is transforming data into strategic principles and business impact.
  <br>
  I have studied and worked in both the United States and France. Please <a href="https://docs.google.com/forms/d/e/1FAIpQLSdaM0dB94QPEt9lZqslmL7no4zA9TQ5sY0UnriuiNYZ7fjk-w/viewform?usp=sf_link"contact me</a> with opportunities in User Research, Product Management, and UX Strategy in either of the countries. 
  <br>
  <a href="https://drive.google.com/file/d/1kZpFV_2Q4WUg9XOAYFo0Le7BWypJrwhb/view?usp=sharing">Résumé (English)</a> | <a href="put link here">CV (français)</a> | <a href="https://www.linkedin.com/in/jill-ti/">LinkedIn</a>
  
google_analytics: UA-171045601-1 # your Google Analytics tracking ID here
theme: jekyll-theme-minimal

