title: Jill Tipton # your name (or website title) here
logo: "/images/641158C6-761D-4D22-88CC-DFF1E73252FE.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A former social science researcher who transitioned to UX Research, I execute quantitative and qualitative research studies to support design decisions and drive product initiatives. My favorite question is “Why?” and I use the answers to develop digital experiences that improve people’s lives. My greatest strength is transforming data into strategic principles and business impact. 
  <br><br>
  <a href="https://www.linkedin.com/in/jill-ti/">LinkedIn</a> 
  
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
theme: e8e7005d4f30780ce0c42eb5f6fb279f01f10b89
